name: build and push

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GROUP: f3lin
      COMMIT: ${{ github.sha }}
      REPO: front-end
      
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        run: make test-front-end

  build-push-image:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.inputs.action == 'push' }}
    env:
      GROUP: f3lin
      REPO: front-end
      COMMIT: ${{ github.sha }}
      AWS_REGION: eu-central-1

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        id: build
        run: |
          chmod +x scripts/build.sh
          bash scripts/build.sh

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          chmod +x scripts/git_update_tag.sh
          bash scripts/git_update_tag.sh -v patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.GROUP }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR Private
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker Image
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker tag ${GROUP}/${REPO}:${COMMIT} ${GROUP}/${REPO}:$IMAGE_TAG
          docker tag ${GROUP}/${REPO}:${COMMIT} ${REGISTRY}/${REPO}:$IMAGE_TAG

      - name: Push Docker Image to Docker Hub
        env:
          TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker push ${GROUP}/${REPO}:${TAG}

      - name: push Frontend docker image to Amazon ECR Private
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker push $REGISTRY/$REPO:$IMAGE_TAG

