name: ci

on:
  push:
    branches:
    - main  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  test:
    permissions:
      contents: write 
    runs-on: ubuntu-latest
    env:
      GROUP: f3lin 
      COMMIT: ${{ github.sha }}
      REPO: front-end
    steps:
    - uses: actions/checkout@v4

    - name: Unit Tests
      run: make test-front-end

    - name: Test sock-shop app
      id: docker-compose
      run: make test-sock-shop

    - name: Wait for Container Termination
      id: wait
      if: steps.docker-compose.outcome == 'success'
      run: |
        while [ "$(docker inspect -f '{{.State.Running}}' front-end-user-sim-1)" == "true" ]; do
          echo "Waiting for front-end-user-sim-1 to terminate..."
          sleep 10
        done
        echo "Container front-end-user-sim-1 has terminated."

    - name: Get Logs from Load-Test Container
      id: logs
      if: steps.wait.outcome == 'success'
      run: |
        docker logs -f front-end-user-sim-1 &> logs.txt || true
        cat logs.txt